recs = <header> rec+
rec = time description id (!time !id stuff)+
time = #"\d+:\d+" <nl>
date = #"\d+/\d+/\d+" <nl>
page = #"Page .*" <nl>
disposition = #"Disposition: (.+)" <nl>
id = #"\d+" <nl>
stuff = #".*" <nl>
description = #".+" <nl>
<nl> =  #"\n+"
<header> = "PACIFICA POLICE DEPARTMENT" <nl> "MEDIA BULLETIN" <nl> #"DAILY.*" <nl>
<pagedelim> = <nl>+ page date <nl>+