recs = header rec+
rec = time type id (!time !id description)+
type = #".+" <nl>
description = #".*" <nl>
time = <nl>* #"\d+:\d+" <nl>+
id = #"\d+" <nl>
<header> = f? <"PACIFICA POLICE DEPARTMENT" <nl> "MEDIA BULLETIN"> <nl> hdate
hdate = <"DAILY --- ">? <#"\S+, "> #"\S+ \d+, \d+" <nl>
<nl> =  #"\n+" f?
<f> = <"\f"?>