name: check-and-test
on: push
jobs:
  check:
    name: Run lein check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lein check
        run: lein update-in : assoc :pedantic? :warn -- check
